version: "3"
services: 
    pytorch:
        build:
            context: .
            args:
                - USER_NAME=${USER_NAME}
                - USER_UID=${USER_UID}
                - USER_GID=${USER_GID}
        working_dir: /workspace
        tty: true
        volumes: 
            - ./:/workspace:cached
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
        shm_size: "2gb"